# Generated by Django 4.1.3 on 2022-11-19 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aeroporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'aeroporto',
            },
        ),
        migrations.CreateModel(
            name='companhia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'companhia_aerea',
            },
        ),
        migrations.CreateModel(
            name='orq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida_prev', models.TimeField(null=True)),
                ('chegada_prev', models.TimeField(null=True)),
                ('saida_real', models.TimeField(null=True)),
                ('chegada_real', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('EM', 'Embarcando'), ('CA', 'Cancelado'), ('PR', 'Embarcando'), ('TA', 'Taxeando'), ('PO', 'Pronto'), ('AU', 'Autorizado'), ('VO', 'Em voo'), ('AT', 'Aterrisado')], default='EM', max_length=2)),
            ],
            options={
                'db_table': 'orq',
            },
        ),
        migrations.CreateModel(
            name='voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('origem', models.CharField(max_length=3)),
                ('destino', models.CharField(max_length=3)),
                ('companhia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voos.companhia')),
            ],
            options={
                'db_table': 'voo',
            },
        ),
    ]
